# Generated by Django 5.1.5 on 2025-01-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
