# Generated by Django 5.1.5 on 2025-01-31 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('transacoes', '0002_alter_transacao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='contas.conta'),
            preserve_default=False,
        ),
    ]
